### ISSUE TITLE
Messed up spacing

### ISSUE THREAD

**Issue by JohnReedLOL** [JohnReedLOL/scala-trace-debug#12]
Input:

```
      println("an error message" + Pos())
      println(Log.find("foo" + 2 + "bar"))
      SDebug.traceCode("foo" + 2 + "bar")
      SDebug.traceExpression("foo" + 2 + "bar")
      SDebug.traceContents(List(1,2,3))
      println(Log.find(List(1,2,3)))
```

Output:

```
an error message - Main.main(Main.scala:118)
("foo" + 2 + "bar") ->foo2bar - Main.main(Main.scala:119)

"("foo" + 2 + "bar") -> foo2bar" in thread main:
	at Main$.main(Main.scala:120)

""foo".+(2).+("bar") -> foo2bar" in thread main:
	at Main$.main(Main.scala:121)

"Contains: Int 1, 2, 3
" in thread main:
	at Main$.main(Main.scala:122)
```

```
("foo" + 2 + "bar") ->foo2bar - Main.main(Main.scala:119)
```

is supposed to be

```
("foo" + 2 + "bar") -> foo2bar - Main.main(Main.scala:119)
```

**Comment by JohnReedLOL** [comment]
Spacing appears consistent
