### ISSUE TITLE
Doesn't work with Java 7

### ISSUE THREAD

**Issue by JohnReedLOL** [JohnReedLOL/scala-trace-debug#15]
If I run it with Java 7, I get...

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: scala/trace/internal/PackagingDataCalculator : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at scala.trace.internal.Printer$.getPackageName(Printer.scala:142)
	at scala.trace.internal.Printer$$anonfun$traceInternal$1.apply$mcVI$sp(Printer.scala:106)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:166)
	at scala.trace.internal.Printer$.traceInternal(Printer.scala:103)
	at scala.trace.Debug$.trace(Debug.scala:151)
	at com.example.Hello$.main(Hello.scala:84)
	at com.example.Hello.main(Hello.scala)

Process finished with exit code 1
```

**Comment by JohnReedLOL** [comment]
Solved by publishing with Java 7 using http://stackoverflow.com/questions/7701692/setting-up-sbt-to-use-java-7-for-compilation
