### ISSUE TITLE
No class def found

### ISSUE THREAD

**Issue by JohnReedLOL** [JohnReedLOL/scala-trace-debug#19]
SDebug.traceContents("Foo")

Exception in thread "main" java.lang.NoClassDefFoundError: scala/reflect/runtime/package$
	at Main$.main(Main.scala:9)
	at Main.main(Main.scala)
Caused by: java.lang.ClassNotFoundException: scala.reflect.runtime.package$
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more
Disconnected from the target VM, address: '127.0.0.1:45505', transport: 'socket'

**Comment by JohnReedLOL** [comment]
Solution:

/* Comment out this
def macroDependencies(version: String) =
  Seq(
    "org.scala-lang" % "scala-reflect" % version % "provided",
    "org.scala-lang" % "scala-compiler" % version % "provided"
  )
*/

// Add this
libraryDependencies += "org.scala-lang" % "scala-reflect" % scalaVersion.value

**Comment by JohnReedLOL** [comment]
Added warning to README
